//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WishList.WebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishItem
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string brand { get; set; }
        public string no { get; set; }
        public Nullable<int> price { get; set; }
        public string imageId { get; set; }
        public string currency { get; set; }
        public string comment { get; set; }
        public int status { get; set; }
        public string feedback { get; set; }
    }
}
